### ISSUE TITLE
github raw代理

### ISSUE THREAD

**Issue by wosiwq** [Gaylone/blhx_wiki#1]
fastgit提供了github的raw代理
可考虑将 `https://raw.githubusercontent.com/` 更换为 `https://raw.fastgit.org/` 以满足国内用户的需求

**Comment by Gaylone** [comment]
api封装的，我这不好改，但是可以用离线模式

**Comment by wosiwq** [comment]
> api封装的，我这不好改，但是可以用离线模式

直接替换原文中的raw地址或许可行？ 例如 [L11](https://github.com/Gaylone/blhx_wiki/blob/e2259015233b649a55d22ee057f3392e737316c2/AzurlaneAPI.py#L11)

**Comment by Gaylone** [comment]
我看看

**Comment by Gaylone** [comment]
好用啊兄弟，给你安排了

**Comment by wosiwq** [comment]
我的阿里云遇到了fastgit无法连通的情况 这里再放一个raw代理的地址 给后面fastgit也连不上的兄弟用 `https://raw.githubusercontents.com/` 此链接相较原raw链接多了一个S在末尾 注意区分

**Comment by Gaylone** [comment]
看情况用吧各位，代理配置在AzurlaneAPI主体第一行
