### ISSUE TITLE
柴郡无法查询

### ISSUE THREAD

**Issue by likingsdee** [Gaylone/blhx_wiki#10]
如题，附上log
![image](https://user-images.githubusercontent.com/37286077/141891665-282c0358-1280-4cf8-bee5-7b784ddff1d1.png)

**Comment by Gaylone** [comment]
已修复

**Comment by likingsdee** [comment]
已测试，柴郡可以查询，新bug，所有舰船搜索都不显示立绘了
![QQ图片20211116170655](https://user-images.githubusercontent.com/37286077/141955770-7b0a8832-4276-4e1a-8c6c-67ebff9d0473.png)
![image](https://user-images.githubusercontent.com/37286077/141956016-d810fdac-a773-4650-bda5-cfbe9feef344.png)
![image](https://user-images.githubusercontent.com/37286077/141956059-dac12b62-6c72-449b-92dc-6b4da77e0ff1.png)

**Comment by Gaylone** [comment]
现在呢

**Comment by likingsdee** [comment]
OK
