### ISSUE TITLE
处理方式效率太低

### ISSUE THREAD

**Issue by wosiwq** [Gaylone/blhx_wiki#2]
经测试即使提前离线了数据 在调用命令 如 `blhx 长门` 时 仍需处理超过1分钟的时间 且处理时整个hoshinobot处于停滞状态 无法接收和处理任何消息
![image](https://user-images.githubusercontent.com/45610776/130313737-5dd64b0b-2c86-4fe8-8d9c-5fe81709570d.png)

**Comment by Gaylone** [comment]
每次都这样还是偶尔呢

**Comment by wosiwq** [comment]
> 每次都这样还是偶尔呢

每次 只要执行该插件相关的指令 就会直接占用整个bot

**Comment by Gaylone** [comment]
优化了，现在看看

**Comment by wosiwq** [comment]
经实测效率大幅提升 原本需要一分钟以上的处理时间 现在约需要5s
