### ISSUE TITLE
希望增加舰船的别名系统

### ISSUE THREAD

**Issue by Mythe51** [Gaylone/blhx_wiki#4]
在查询的时候，现有的查询只支持舰船名完全匹配，难以应对以下情况：
1. 重樱舰船只能使用非和谐名查询
2. 某些名字中含有点的舰船查询困难。例如【海伦娜·META】，使用【海伦娜・META】就查不到
![image](https://user-images.githubusercontent.com/56372353/133553795-8c3380df-1367-4a2a-bb31-c9577c13a26b.png)

希望能在系统中加入全局的别名翻译模块，输入例如“海妈”，“黑海妈”的时候可以自动翻译成标准的舰船名。
在实现上，可以参考公主连结priconne模块中对人物别名的处理。

（我的话想参与到这个模块的开发当中，如果可以的话还望大佬给个联系方式）

**Comment by Gaylone** [comment]
好啊啊啊啊，加我qq  945444204 暗号是   不敢高声暗皱眉

**Comment by Gaylone** [comment]
已搞定，原型已推出
