### ISSUE TITLE
希望增加使用序号指定皮肤的功能。

### ISSUE THREAD

**Issue by wangjiahui1126** [Gaylone/blhx_wiki#5]
要打全皮肤名才能查询，有的皮肤名字还有英文大小写，实际查询时遇到了麻烦
一个小建议。感谢项目主的无私贡献，已点星星

**Comment by Gaylone** [comment]
你好，目前不仅有英文大小写的区分，甚至包含部分日语字符，法文字符，有待后续优化

**Comment by Gaylone** [comment]
现在可以依据查询结果里的皮肤列表，通过相关指令查询，详情看命令模板
